CONFIG_NAME: bird

dataset_name: birds
data_dir: ../data/birds

gpu_id: 0
num_workers: 16
imsize: 256
z_dim: 100
cond_dim: 256
manual_seed: 100
cuda: True

stamp: 'normal'
state_epoch: 0
max_epoch: 800
batch_size: 16
nf: 32
ch_size: 3

model: base

gen_interval: 1
test_interval: 1
save_interval: 1

truncation: True
trunc_rate: 0.88

sample_times: 10
npz_path: ../data/birds/npz/bird_val256_FIDK0.npz
example_captions: ./example_captions/bird.txt
samples_save_dir: ./samples/bird/
checkpoint: ./saved_models/bird/pretrained/state_epoch_1220.pth

save_image: False
val_save_dir: ./vals/bird/

TEXT:
    WORDS_NUM: 18
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
    DAMSM_NAME: ../data/birds/DAMSMencoder/text_encoder200.pth

TRAIN:
    FLAG: True
    NET_GEN: ''  # '../models/bird_AttnGAN2.pth'
    B_NET_D: True
<<<<<<< HEAD
    BATCH_SIZE: 20  # 22
    MAX_EPOCH: 600
    SNAPSHOT_INTERVAL: 10
    DISCRIMINATOR_LR: 0.0005
    GENERATOR_LR: 0.0005
    #
    TEXT_ENC: '../DAMSMencoders/bird/text_encoder200.pth'
=======
    DISCRIMINATOR_LR: 0.0005
    GENERATOR_LR: 0.0005
>>>>>>> ad96f4a352e5e956e392ced1bb15ed35eb24d38f
    SMOOTH:
        GAMMA1: 4.0  # 1,2,5 good 4 best  10&100bad
        GAMMA2: 5.0
        GAMMA3: 10.0  # 10good 1&100bad
        LAMBDA: 5.0

GAN:
    DF_DIM: 32
    GF_DIM: 64
    Z_DIM: 100
    RES_NUM: 3
<<<<<<< HEAD

=======
    CONDITION_DIM: 100
>>>>>>> ad96f4a352e5e956e392ced1bb15ed35eb24d38f
